version: 2.1

jobs:
  check:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm run lint

workflows:
  check:
    jobs:
      - check
